"""Adicionar campo valor_formatado

Revision ID: 56d12c875d1b
Revises: 
Create Date: 2025-11-17 17:34:16.588884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d12c875d1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brainrot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_formatado', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brainrot', schema=None) as batch_op:
        batch_op.drop_column('valor_formatado')

    # ### end Alembic commands ###
